# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc91987c33ef45f2b10bf9bda6de9fae8fbb9a037bb2f72712dd1f3ab40efaca33b4603945d114c534a06ff8b0d78d5d37bba41175cc08443a4d3d8960d8f518

test:
  secret_key_base: ac4a2609950b149dbb51aa4dc755b1412554676ac598d21972477cc5e9a246cdaacfc9e8a0d8e593fcc89faf16e652aff7bf8bcf27ebfda630d103f53dee8ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
